CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    picture_url character varying(255)
);

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status character varying(255)
);

CREATE TABLE product_info (
    product_id bigint PRIMARY KEY REFERENCES product(id),
    name character varying(255) NOT NULL,
    price double precision
);

CREATE TABLE orders_date (
    order_id bigint PRIMARY KEY REFERENCES orders(id),
    status character varying(255),
    date_created date DEFAULT CURRENT_DATE
);

CREATE TABLE order_product (
    quantity integer NOT NULL,
    order_id bigint NOT NULL REFERENCES orders(id),
    product_id bigint NOT NULL REFERENCES product(id),
    PRIMARY KEY (order_id, product_id)
);