name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Setup Flyway CLI
      uses: red-gate/setup-flyway@v1
      with:
          # Use "community", "teams", or "enterprise"
          edition: community
          # Set to true to consent to the Redgate EULA
          i-agree-to-the-eula: true
    
    #### Добавьте шаг с Flyway-миграциями
    - run: |
        flyway migrate \
            -url=${{ secrets.DB_URL }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASS }} \
            -locations=filesystem:./migrations

    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}